### ISSUE TITLE
Breaking changes in Az.Network

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1163]
## :computer: System information

- Operating System: All
- Data Safe Haven version: All
- Powershell version: 7.2.5
- `Az` Powershell module version: 8.1.0
- `Microsoft.Graph` Powershell module version: 1.10.0
- `Poshstache` module version: 0.1.10
 
## :strawberry: Desired behaviour

Scripts will continue to run in new `Az.Network` versions

## :no_entry_sign: Actual behaviour

Breaking changes in `Az.Network`

```
WARNING: Upcoming breaking changes in the cmdlet 'New-AzFirewall' :

- The parameter : 'VirtualNetworkName' is being replaced by parameter : 'VirtualNetwork'.
The type of the parameter is changing from 'System.String' to 'PSVirtualNetwork'.
- Change description : This parameter will be removed in an upcoming breaking change release. After this point the Virtual Network will be provided as an object instead of a string.
- The change is expected to take effect from the version : '2.0.0'
Cmdlet invocation changes :
    Old Way : New-AzFirewall -VirtualNetworkName "vnet-name"
    New Way : New-AzFirewall -VirtualNetwork $vnet

- The parameter : 'PublicIpName' is being replaced by parameter : 'PublicIpAddress'.
The type of the parameter is changing from 'System.String' to 'List<PSPublicIpAddress>'.
- Change description : This parameter will be removed in an upcoming breaking change release. After this point the Public IP Address will be provided as a list of one or more objects instead of a string.
- The change is expected to take effect from the version : '2.0.0'
Cmdlet invocation changes :
    Old Way : New-AzFirewall -PublicIpName "public-ip-name"
    New Way : New-AzFirewall -PublicIpAddress @($publicip1, $publicip2)
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
```

## :recycle: To reproduce

Upgrade to `Az.Network >= 2.0.0` when our scripts should fail.

**Comment by craddm** [comment]
Not really clear what to do about this change. `Az.Network` is currently up to version `6.2.0` and the parameters are still shown in the documentation (https://learn.microsoft.com/en-us/powershell/module/az.network/new-azfirewall?view=azps-10.4.1). We already have `5.3.0` as the required version in our scripts.

We *could* try switching to the new syntax, since we already require a later version of `Az.Network`.

It seems a bit confusing how MS seem to include two versions of the commands in the documentation: one with the old parameters, and one with the new. According to the release notes, the parameters were deprecated in version [`2.3.2`](https://learn.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-10.4.1#232---june-2019). But it doesn't really seem like these are really *breaking* changes, as the old parameter names never seem to be removed.
