### ISSUE TITLE
Requiring unmaintained Powershell

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1361]
`CheckRequirements.ps1` enforces a maximum Powershell version of 7.2.7.

Currently, 7.2 is in LTS with 7.2.8 being the current minor version. 7.3 is the latest stable release.

This will likely cause problems for users where package managers will not have 7.2.7.
This is the case [for snapcraft](https://snapcraft.io/powershell) and is causing CI to [fail](https://github.com/alan-turing-institute/data-safe-haven/actions/runs/4005323754/jobs/6875541112) as 7.2.8 is [installed on the runners](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)

See #1332

**Comment by craddm** [comment]
I could 1) check if 7.2.8 hits the same issues as 7.3 with our current set of required modules and/or 2) check if updating our current required modules to versions that don't have problems with 7.3 creates any other issues?

**Comment by jemrobinson** [comment]
Sounds good if you have some time @craddm

**Comment by jemrobinson** [comment]
Is it actually only `7.3.0` that has the problem? Looks like `7.3.1` [might be fixed](https://github.com/Azure/azure-powershell/issues/18721)

**Comment by craddm** [comment]
Possibly, planning to look this afternoon! The problem was with the combination of 7.3 and some earlier versions of the modules and could be fixed either by updating the modules or downgrading powershell. I mistakenly assumed that as they'd gone to 7.3.x there wouldn't be a 7.2.8+... as I recall at the time some of the preview versions of what would be 7.3.1 were supposed to fix some of the problems

**Comment by craddm** [comment]
Still having the same issues with 7.3.1 installed (without updating any modules), will investigate further. 

Some similar issues with 7.2.8 (at least those involving MS Graph), so will have to look at updating the individual modules too.

**Comment by jemrobinson** [comment]
Looks like Powershell 7.3.2 also exists now. If that works, maybe we need to exclude eg. 7.2.8, 7.3.0 and 7.3.1?

**Comment by craddm** [comment]
Will try that. With 7.2.8, the Az modules are fine ~but the MS Graph ones are broken~ - retested today and 7.2.8 seems fine, not sure what was causing the issue with MS Graph yesterday but can't replicate it. Apparently there's a 7.2.9 as well...

**Comment by craddm** [comment]
Ok, same problem on 7.3.2, so I'll just try updating the modules and test them on a couple of Powershell versions tomorrow

**Comment by craddm** [comment]
Right, so here's where I think we're at.

Versions < 7.3.0 are fine without further action.

Version 7.3.0 needs updates to several Az modules. For some reason, with Powershell 7.3.0, one of the Microsoft Graph modules installs as version 1.20.0 instead of 1.10.0, while the others are 1.10.0 (the minimum specified in the requirements). Updating the Graph modules fixes this. For Powershell 7.3.1 and above, MS Graph installs 1.10.0 for all modules as expected, and works fine, but the Az modules all need updating.

So far as I can tell, Powershell < 7.3.0 works fine with updated modules - at least with 7.2.8 everything I've tried works - so maybe the best option is to update the required versions of the modules and dispense with the upper limit on Powershell versions.
