### ISSUE TITLE
Failing Julia smoke tests

### ISSUE THREAD

**Issue by helen-d-little** [alan-turing-institute/data-safe-haven#1679]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:** 4.1.0

## :no_entry_sign: Describe the problem

When running smoke tests on the DSG (Ignota) VM (Standard_NC8as_T4_v3) the first smoke test - Julia Packages - fails with the following error messages. All other tests pass. The Julia packages test passes on the CPU-VM (Standard D2s v3)

## :deciduous_tree: Log messages

```
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 178,
    in test file run_all_tests.bats, line 53)
     `assert_output --regexp 'All [0-9]+ packages are installed'' failed
   
   -- regular expression does not match output --
   regexp (1 lines):
     All [0-9]+ packages are installed
   output (83 lines):
     Testing 42 Julia packages
     Invalid instruction at 0x7fc3a4dcc4d1: 0x62, 0xf1, 0xd5, 0x08, 0xc2, 0xc7, 0x00, 0x62, 0xf1, 0xe5, 0x08, 0xc2, 0xcf, 0x04, 0xc5
   
     [4044] signal (4.2): Illegal instruction
     in expression starting at none:1
     ifelse at ./essentials.jl:575 [inlined]
     mul12 at ./twiceprecision.jl:116 [inlined]
     / at ./twiceprecision.jl:332
     / at ./twiceprecision.jl:327 [inlined]
     TwicePrecision at ./twiceprecision.jl:225 [inlined]
     steprangelen_hp at ./twiceprecision.jl:346
     _linspace at ./twiceprecision.jl:734
     _linspace at ./twiceprecision.jl:718 [inlined]
     range_start_stop_length at ./range.jl:578 [inlined]
     _range at ./range.jl:161 [inlined]
     #range#70 at ./range.jl:142 [inlined]
     range at ./range.jl:142 [inlined]
     get_range at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:291 [inlined]
     #cgrad#11 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:233 [inlined]
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:227 [inlined]
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:227
     jfptr_cgrad_1709 at /opt/julia/julia-1.9/depot/compiled/v1.9/PlotUtils/YveHG_LQHzj.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     #cgrad#12 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:239
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:237 [inlined]
     #default_cgrad#14 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:244 [inlined]
     default_cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:244 [inlined]
     #_theme#182 at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:24
     _theme at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:16 [inlined]
     #theme#181 at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:13
     theme at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:6 [inlined]
     _plots_theme_defaults at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/init.jl:21
     __init__ at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/init.jl:36
     unknown function (ip: 0x7fc3dfc4d92f)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     jl_module_run_initializer at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:75
     ijl_init_restored_modules at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/module.c:982
     register_restored_modules at ./loading.jl:1115
     _include_from_serialized at ./loading.jl:1061
     _require_search_from_serialized at ./loading.jl:1506
     _require at ./loading.jl:1783
     _require_prelocked at ./loading.jl:1660
     unknown function (ip: 0x7fc3dfc3efc6)
     macro expansion at ./loading.jl:1648 [inlined]
     macro expansion at ./lock.jl:267 [inlined]
     require at ./loading.jl:1611
     unknown function (ip: 0x7fc3dfc3bf56)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     call_require at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:466 [inlined]
     eval_import_path at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:503
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:731
     ijl_toplevel_eval_in at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:971
     eval at ./boot.jl:370 [inlined]
     top-level scope at /opt/tests/tests/test_packages_installed_julia.jl:24
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:903
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:856
     ijl_toplevel_eval_in at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:971
     eval at ./boot.jl:370 [inlined]
     include_string at ./loading.jl:1903
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     _include at ./loading.jl:1963
     include at ./Base.jl:457
     jfptr_include_35036.clone_1 at /opt/julia/julia-1.9/lib/julia/sys.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     exec_options at ./client.jl:307
     _start at ./client.jl:522
     jfptr__start_40034.clone_1 at /opt/julia/julia-1.9/lib/julia/sys.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     true_main at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/jlapi.c:573
     jl_repl_entrypoint at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/jlapi.c:717
     main at julia (unknown line)
     __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
     unknown function (ip: 0x4010b8)
     Allocations: 38069172 (Pool: 38057919; Big: 11253); GC: 60
   --
```

**Comment by dsj976** [comment]
Having a similar issue with the `Python package repository (3.10)` smoke test (sometimes also `Python package repository (3.9)`):

```
✗ Python package repository (3.10)
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 186,
    from function `test_python_repository' in file run_all_tests.bats, line 37,
    in test file run_all_tests.bats, line 91)
     `test_python_repository '3.10'' failed
   
   -- output does not contain substring --
   substring (1 lines):
     All package installations behaved as expected
   output (8 lines):
     rm: cannot remove '/home/david.sjasin/test-repository-python/lib/python3.11/site-packages': Directory not empty
     Attempting to install absl-py...
     tests/test_repository_python.sh: line 22: /home/david.sjasin/test-repository-python/bin/pip: No such file or directory
     ... absl-py installation failed
     Attempting to install zope.interface...
     tests/test_repository_python.sh: line 22: /home/david.sjasin/test-repository-python/bin/pip: No such file or directory
     ... zope.interface installation failed
     One or more package installations did not behave as expected!
```

**Comment by dsj976** [comment]
Should note that I ran tests on a single VM straight after SRE deployment and they all passed. These test failures are arising more than a week after deployment

**Comment by JimMadge** [comment]
@helendduncan Can you reproduce the problem on any other SRD?
It is hard to see what is going on from the trace, but the invalid instruction message and the fact it goes all the way to glibc makes me suspect it's probably not to do with the test.

**Comment by JimMadge** [comment]
@dsj976 That looks to be another issue. Looks like the Python install is not correct, `pip` doesn't exist.

I'm not sure why the directory isn't being deleted, the test script uses `rm -rf`. You could try removing that directory manually and running again.

**Comment by helen-d-little** [comment]
> @helendduncan Can you reproduce the problem on any other SRD? It is hard to see what is going on from the trace, but the invalid instruction message and the fact it goes all the way to glibc makes me suspect it's probably not to do with the test.

The test fails for both GPU-enabled VMs under the Ignota subscription but passes for the CPU VM. Will test for another subscription now and edit this message

Test also fails for the JMAT subscription GPU-VM with the following error message

```
 ✗ Julia packages
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 178,
    in test file run_all_tests.bats, line 53)
     `assert_output --regexp 'All [0-9]+ packages are installed'' failed
   
   -- regular expression does not match output --
   regexp (1 lines):
     All [0-9]+ packages are installed
   output (83 lines):
     Testing 42 Julia packages
     Invalid instruction at 0x7f1b4c81d4d1: 0x62, 0xf1, 0xd5, 0x08, 0xc2, 0xc7, 0x00, 0x62, 0xf1, 0xe5, 0x08, 0xc2, 0xcf, 0x04, 0xc5
   
     [588433] signal (4.2): Illegal instruction
     in expression starting at none:1
     ifelse at ./essentials.jl:575 [inlined]
     mul12 at ./twiceprecision.jl:116 [inlined]
     / at ./twiceprecision.jl:332
     / at ./twiceprecision.jl:327 [inlined]
     TwicePrecision at ./twiceprecision.jl:225 [inlined]
     steprangelen_hp at ./twiceprecision.jl:346
     _linspace at ./twiceprecision.jl:734
     _linspace at ./twiceprecision.jl:718 [inlined]
     range_start_stop_length at ./range.jl:578 [inlined]
     _range at ./range.jl:161 [inlined]
     #range#70 at ./range.jl:142 [inlined]
     range at ./range.jl:142 [inlined]
     get_range at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:291 [inlined]
     #cgrad#11 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:233 [inlined]
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:227 [inlined]
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:227
     jfptr_cgrad_1709 at /opt/julia/julia-1.9/depot/compiled/v1.9/PlotUtils/YveHG_LQHzj.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     #cgrad#12 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:239
     cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:237 [inlined]
     #default_cgrad#14 at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:244 [inlined]
     default_cgrad at /opt/julia/julia-1.9/depot/packages/PlotUtils/mHQ0Q/src/colorschemes.jl:244 [inlined]
     #_theme#182 at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:24
     _theme at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:16 [inlined]
     #theme#181 at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:13
     theme at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/themes.jl:6 [inlined]
     _plots_theme_defaults at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/init.jl:21
     __init__ at /opt/julia/julia-1.9/depot/packages/Plots/3BCH5/src/init.jl:36
     unknown function (ip: 0x7f1b8761992f)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     jl_module_run_initializer at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:75
     ijl_init_restored_modules at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/module.c:982
     register_restored_modules at ./loading.jl:1115
     _include_from_serialized at ./loading.jl:1061
     _require_search_from_serialized at ./loading.jl:1506
     _require at ./loading.jl:1783
     _require_prelocked at ./loading.jl:1660
     unknown function (ip: 0x7f1b8760afc6)
     macro expansion at ./loading.jl:1648 [inlined]
     macro expansion at ./lock.jl:267 [inlined]
     require at ./loading.jl:1611
     unknown function (ip: 0x7f1b87607f56)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     call_require at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:466 [inlined]
     eval_import_path at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:503
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:731
     ijl_toplevel_eval_in at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:971
     eval at ./boot.jl:370 [inlined]
     top-level scope at /opt/tests/tests/test_packages_installed_julia.jl:24
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:903
     jl_toplevel_eval_flex at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:856
     ijl_toplevel_eval_in at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:971
     eval at ./boot.jl:370 [inlined]
     include_string at ./loading.jl:1903
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     _include at ./loading.jl:1963
     include at ./Base.jl:457
     jfptr_include_35036.clone_1 at /opt/julia/julia-1.9/lib/julia/sys.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     exec_options at ./client.jl:307
     _start at ./client.jl:522
     jfptr__start_40034.clone_1 at /opt/julia/julia-1.9/lib/julia/sys.so (unknown line)
     _jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
     ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
     jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
     true_main at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/jlapi.c:573
     jl_repl_entrypoint at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/jlapi.c:717
     main at julia (unknown line)
     __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
     unknown function (ip: 0x4010b8)
     Allocations: 38069541 (Pool: 38058285; Big: 11256); GC: 61
   --
```

**Comment by craddm** [comment]
`Standard_D2s_v3` and `Standard_NC8as_T4_v3` have different CPU architectures - Intel vs AMD. Best guess is that the VM images have precompiled versions for Intel CPU architectures, not for AMD.

May need to do something like this: https://github.com/JuliaLang/julia/issues/49705#issuecomment-1776167639 

Corollary to that is that a GPU VM (like NCv3-series) using an Intel CPU shouldn't have this problem

**Comment by JimMadge** [comment]
I did suspect that and wonder if one size was ARM. Both are x86_64 so I thought it was unlikely. You don't tend to see different builds for Intel and AMD for example, you can query what instructions a CPU has an choose an appropriate routine.

Maybe some library is trying to use avx-512 or similar instructions though, Julia is quite focused on performance where it would be worth taking advantage of these if they are available.

**Comment by craddm** [comment]
Just to confirm I have also replicated this on a non-GPU AMD-based VM (D2as_V4). Adding `--pkgimages=no` didn't help.

The `Plots` package seems to be the culprit. Unsure whether this is a bug specific to that package, or to this version of Julia, or both. As yet unable to find a way round it.

**Comment by craddm** [comment]
Ok, definitely the precompiled cached versions of packages that are causing the problem. Managed to manually delete cached version of `Plots` on the SRD and now it runs without issues after recompiling the package. Will hopefully find a way around this that works at the VM image level. Should be able to specify the relevant environment variable in the cloud-init file in a way that allows it to support both AMD and Intel CPUs. 

This might still be a future issue with new CPU types etc...

**Comment by JimMadge** [comment]
Oh, now that makes a lot of sense. The package has been compiled (JIT?) for one target, then we move the filesystem over to another :bulb:.

Does this happen because the smoketests are first run on an Intel CPU before an AMD CPU?
Does compilation of some packages happen at install time to make them faster?

**Comment by craddm** [comment]
They're already built on the VM image. I think it's this line from the build image `cloud-init`:

```
- MISSING_JULIA_PACKAGES=$(julia -e "for package in $JULIA_PACKAGES; try; abspath(joinpath(dirname(Base.find_package(package)))); @eval using \$(Symbol(package)); catch e; println(package); end; end;")
```

After installing the packages, the script checks if any are missing by loading them using `using` and thus erroring if any haven't actually been installed. `using` is making Julia compile them, and since the VM during this process is on an Intel CPU, it compiles for that. 

Think I'll try to find a way to use `Pkg.status()` to list installed packages and parse that instead. Alternatively, I can specify an environment variable that'll tell it to compile for both Intel and AMD. But the flags get quite specific about the architecture (e.g. you specify `znver3`, not just AMD, and you'd also need `znver2` for older AMD CPUs), that's probably not that future proof. So it's probably best to just find a way to *not* compile the packages during the image building process.

**Comment by craddm** [comment]
Hm, might have a workaround. Fiddling with the `--pkgimages=no` flag at the command line for Julia. Appears using that on the AMD VM forces recompilation of the packages. 

If I do that on the build VM when checking if the packages are installed, it might stop it from  caching the compiled versions and those cached versions being on the SRDs made from the image. Users would have to precompile the packages themselves on first use, but that's normal for Julia anyway.

Another alternative is to set `JULIA_CPU_TARGET=generic`. That might deleteriously impact package performance, as it eschews any CPU specific optimisation. But not clear how much.

**Comment by craddm** [comment]
Right, several possible paths:

1) `--pkgimages=no` on the build VM should stop precompiled packages being stashed on the VM and subsequently causing problems on AMD VMs. However, this requires every user to compile the packages on first use. Seems inefficient compared to the current case, where everybody shares precompiled packages. But it is the most robust way of dealing with variations in CPU types/architectures.
2) Set an environment variable on the build VM that tells it to compile for [multiple micro-architectures](https://docs.julialang.org/en/v1/devdocs/pkgimg/#Package-images-optimized-for-multiple-microarchitectures). Issue with this is if we miss one of the relevant ones. We may need to specify which subset of VMs Julia will work properly on. Seems not always obvious to me. Does mean people will share one set of precompiled images, rather than each user having to compile their own.
3) Document that where issues of this type arise on deployed VMs, running `julia --pkgimages=no` should force recompilation of the package images and thus fix the issues.

**Comment by JimMadge** [comment]
> --pkgimages=no on the build VM should stop precompiled packages being stashed on the VM and subsequently causing problems on AMD VMs.

I don't think this will fix the problem. It can occur whenever changing VM size after running Hulia (is that right?)

Forcing the Julia compiler to not use optimisations sounds like a bad idea.

I would lean on understanding why this happens and how to fix it.
Where are the compiled packages cached? Is it per user?

**Comment by craddm** [comment]
At the moment, when the image is built, all the packages get compiled and stored in a specific folder that is subsequently accessible to all VM users once we get to the stage of deploying it as an SRD. Any user of that SRD then has to use the precompiled version, or run Julia with the `--pkgimages=no` argument to force it to recompile the packages on use. Because the build VM is Intel, using the precompiled versions from the build VM can cause seg faults etc on AMD CPUs.

My solution is *not* forcing the compiler to not use optimisations. I am suggesting stopping Julia from caching the precompiled versions when it builds them on the build VM. I think it is *probably* still worth running the compilation step on the build VM to check the packages have been correctly added. Julia will still download and store the package sources, which will then be accessible to all SRD users later on. 

What that means is that when they come to use Julia on the SRD, they have to precompile the package themselves. It would then be cached per user, so each separate user would need to precompile the package on the SRD. Since the compilation of the package then happens on the SRD, it'll be compiled for the CPU it is running on, with all the right optimizations. But it does mean they have to spend a lot of time compiling the packages etc on first use, and duplicate compiled versions of the packages - one per user using the package.

**Comment by JimMadge** [comment]
I still don't understand what actually happens when the image is built.

Where are the compiled packages stored for global use? Is that part of `Pkg.Add` or an extra step we do?
I expect that would cause problems if the architecture ever changes, a use will need to instruct Julia to ignore those compiled packages and make new ones.

My feeling is the best solution is to understand how to force re-compiling packages globally, and do this whenever architecture changes.
Some of the packages we install globally are quite large so compiling on first run (or worse every time) could add big delays.

This would also be true for any other software we compile. We don't do much of that at the moment, but may do.

**Comment by craddm** [comment]
From discussion today, probably best to document the process of recompiling the images globally when deploying an SRD on a different CPU arch than the build VM, rather than not caching images at all.

Incidentally, from a bit further reading around, it looks like caching the native code is a relatively recent feature [v1.9+ Julia, released March 2023](https://julialang.org/blog/2023/04/julia-1.9-highlights/#caching_of_native_code). So before then, we'd have been doing something closer to *not* providing compiled versions globally and making users precompile the packages themselves on use. We wouldn't have had these problems, as only non-native code was cached!

**Comment by JimMadge** [comment]
Interesting find. The JIT nature of Julia has been a bit of a double edged sword. 

Particularly annoying when trying to do things like plotting in the REPL.

I recall there were a lot of questions in their forums/issue tracker along the lines of "Why is this so slow first time" or "Why is this algorithm slower than Python" to which the answer was almost always you are including the compilation time.

**Comment by craddm** [comment]
Further update: it looks like the latest release of Julia (v1.10) detects when the cached code was compiled for a different CPU/arch. Doesn't seem to be documented in the release notes, but I've seen it brought up in some Github issues and can confirm that on an AMD based VM it forces recompilation. I think the new cache will be per-user rather than global, so we may still want to document how to do it globally. But at least for now it's less of an issue than it was.
