### ISSUE TITLE
Pulumi: Context with multiple administrators

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1714]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS 13.6.3
- **Data Safe Haven version:** `python-migration`

## :no_entry_sign: Describe the problem

Previously, config files always lived in Azure storage and could only be interacted with programmatically. This meant that multiple administrators attempting to make a change (e.g. adding a new SRE) were always in sync with existing changes.

The new setup involves editing a local file and then uploading it manually. This introduces the possibility of something like the following:

AdminA: Deploys SHM (local file has SHM)
AdminA: Deploys SRE Alpha (local file has SHM and SRE Alpha)
AdminB: Downloads config file, deploys SRE Beta (local file has SHM, SRE Alpha and SRE Beta)
AdminA: Does not download updated config file but deploys SRE Gamma (local file has SHM, SRE Alpha and SRE Gamma)

This means that SRE Beta will be removed from the config version stored in Azure and it's also quite likely that neither AdminA nor AdminB will notice that this has happened.

## :recycle: To reproduce

Do the above

## :strawberry: Suggested change

Some possibilities include:

1. switch back to requiring users to provide input at the command line rather than by editing YAML themselves
2. switch from the current method of directly editing the master config file to instead creating a new file (for just the SHM or just a new SRE) that the code will then merge into the canonical file that lives in Azure storage

I personally think there could be some useful mileage in (2) - it would simplify the thing we're asking users to do ("just write a config section for your SRE") and also remove the possibility that they might delete something important like the pulumi stack information.

**Comment by JimMadge** [comment]
> AdminA: Deploys SHM (local file has SHM)
AdminA: Deploys SRE Alpha (local file has SHM and SRE Alpha)
AdminB: Downloads config file, deploys SRE Beta (local file has SHM, SRE Alpha and SRE Beta)
AdminA: Does not download updated config file but deploys SRE Gamma (local file has SHM, SRE Alpha and SRE Gamma)

I believe this isn't possible (bug notwithstanding). There is no "local config" and deploy commands _always_ use the configuration in the context's storage account. Uploading a configuration is just the (current) way to set what the shared configuration is.

That said, you could simply upload without checking and overwrite another's changes. The longer term plan was to add diff checks and user confirmation when making modifications to the config (#1690). I prefer this to managing lots of command line options or extra files for automatically editing the configuration, which I think overcomplicate the task.

I'm sure @craddm and I have talked about this in Issue/PR comments. I'll have a look for that :eyes:.

> and also remove the possibility that they might delete something important like the pulumi stack information.

I want to move the stack information specifically somewhere else (#1689).
Otherwise, I suppose it is still possible but it feels wrong to me to spend effort trying to stop people _actively_ deleting chunks of their configuration.

**Comment by jemrobinson** [comment]
> That said, you could simply upload without checking and overwrite another's changes.

Yes, this is the scenario I was trying to outline above. Both AdminA and AdminB have a local file called `config.yaml` that they (lazily) reuse instead of downloading from Azure. This results in SRE Beta being overwritten in the config file on Azure when AdminA uploads the second time.

With the previous setup, this wouldn't be possible, as you never edit the file directly and the `dsh` code that was handling it would never have a local file at all - it was all handled in memory.

**Comment by craddm** [comment]
> I'm sure @craddm and I have talked about this in Issue/PR comments. I'll have a look for that 👀.
> 

There was some discussion with this PR - https://github.com/alan-turing-institute/data-safe-haven/pull/1655

**Comment by JimMadge** [comment]
> Yes, this is the scenario I was trying to outline above. Both AdminA and AdminB have a local file called config.yaml that they (lazily) reuse instead of downloading from Azure. This results in SRE Beta being overwritten in the config file on Azure when AdminA uploads the second time.

Yep, that is totally possible and wouldn't (currently) give any feedback.
The way I'd like to handle that is by displaying the diff and prompting the user to confirm changes.

I can also imagine other user experience improvements. `dsh config edit` could _force_ fetch the remote config before editing. I do think the risk of "I've already got a config here, the remote probably hasn't changed since I last uploaded" is fairly high.

**Comment by jemrobinson** [comment]
A possible idea about how editing configs might work

```bash
dsh config sre sandbox show > local.yaml # this can write out the version stored in Azure if it exists, or a template if not
<edit the file>
dsh deploy sre sandbox --config local.yaml
<this command prints out "the old config was X, the new config is Y; is that what you want?">
```
