### ISSUE TITLE
Fix or remove legacy workflows

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1780]
Workflows to,

- Update SRD packages (debs not on the ubuntu repos)
- Update package allowlists for PyPI and CRAN

are currently failing.

We need to either fix these to work with the next release or remove them if they are no longer needed.

**Comment by jemrobinson** [comment]
I think you just deleted the files that these workflows change!

**Comment by JimMadge** [comment]
Would they be used if there were still there?

(Assuming they were at `/deployment/secure_research_desktop/...`)

**Comment by jemrobinson** [comment]
For the moment yes (because the Pulumi code currently builds images on-the-fly without using a gallery). We could either:

- restore `/deployment/secure_research_desktop` for the moment
- prioritise integrating `bureau` into this workflow
- decide that on-the-fly builds that only pre-install a small number of tools are good enough for our next release

**Comment by JimMadge** [comment]
Agreed, we should decide that. I would lean towards stock Ubuntu with minimal changes for simplicity and looking forward to Bureau in the following release.

I think we should be careful not to put too much into the 5.0.0rc2 and (for the moment) keep it to the essentials.
