### ISSUE TITLE
Assigning MFA licenses to users may be a redundant step

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#1986]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

[This step](https://data-safe-haven.readthedocs.io/en/latest/roles/system_manager/manage_users.html#assign-mfa-licences) in the docs might be redundant. See discussion in alan-turing-institute/trusted-research#312. As a system manager, I've never had to complete this step.

## :memo: Required documentation changes

Remove this step from the docs if not necessary, or clarify under which circumstances it is required to complete this step.

**Comment by jemrobinson** [comment]
Microsoft state that this is required to enable self-service password reset: https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-licensing. I've found that in practice, not all users need to have a licence assigned, but I'm not sure of the exact requirement.

**Comment by craddm** [comment]
As I say in the comments on that thread, my understanding is that having any user on the tenant with the relevant license enables SSPR - among other things - for all users, even those without a license.

As it says on the page you link, @jemrobinson, 

> Some tenant services are not currently capable of limiting benefits to specific users. Efforts should be taken to limit the service benefits to licensed users. 

So either you're supposed to give all users licenses, or you're supposed to somehow stop users from using things they don't have licenses for, because Azure can't stop them.

I'd say the docs aren't redundant, exactly - they describe the process you're *supposed* to follow, it's just that it's not technically necessary to follow that process to make things work the way they're supposed to. I'm sure we would of course expect all users of our codebase to follow appropriate legal requirements.

**Comment by JimMadge** [comment]
@craddm Is there more to discuss here or it this a wont fix?

**Comment by JimMadge** [comment]
@craddm said we should keep open as the docs could be clarified.

**Comment by jemrobinson** [comment]
Licences are required both for SSPR and to enable Conditional Access policies. This is clarified in the docs by #2039.
