### ISSUE TITLE
Documentation for generating a SAS token/url for ingress/egress

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2146]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

The security checklist directs readers to an administrator document in several places (e.g. https://data-safe-haven--2141.org.readthedocs.build/en/2141/deployment/security_checklist.html#check-that-the-role-system-manager-can-send-an-upload-token-to-the-role-data-provider-representative-over-a-secure-channel) that doesn't exist. 

## :memo: Required documentation changes

Add some documentation explaining what permissions access tokens require etc

**Comment by craddm** [comment]
@JimMadge Looking back at the history of this, it seems this information (and everything else in the System Manager section) was deleted a while back - [PR here](https://github.com/alan-turing-institute/data-safe-haven/pull/1766) - with the intention of putting (at least) some of it in the [TRESA docs](https://github.com/alan-turing-institute/trusted-research/issues/334).

Do we want to reinstate it to the DSH docs entirely? Some of the deleted information seems to have crept back in to the top-level `Management` section anyway.

**Comment by JimMadge** [comment]
> Do we want to reinstate it to the DSH docs entirely?

Probably not. Much of what we removed was either out of date or too specific (_e.g._ it was talking about one particular team's processes rather than how DSH works or general recommendations) but it was also about _resetting_ the docs. So, a lot of task now is reintroducing and updating those parts which are still relevant.

I would guess the old docs are probably a great starting place though and will get us most of the way there.
